KPI_CATALOG = [
    {
        "kpi":         "Revenue",
        "definition":  "Total revenue attributed to ad-driven conversions in the period.",
        "formula":     "SUM(revenue)",
        "owner":       "Ads Finance",
        "source_table":"fact_campaign_performance",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance → conversions × avg_order_value",
    },
    {
        "kpi":         "Spend",
        "definition":  "Total advertising dollars spent across all campaigns in the period.",
        "formula":     "SUM(spend)",
        "owner":       "Ads Finance",
        "source_table":"fact_campaign_performance",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance → spend",
    },
    {
        "kpi":         "ROAS",
        "definition":  "Return on Ad Spend. Revenue generated per dollar of advertising spend. ROAS > 1 = profitable.",
        "formula":     "SUM(revenue) / SUM(spend)",
        "owner":       "Ads Finance",
        "source_table":"fact_campaign_performance",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance → revenue / spend",
    },
    {
        "kpi":         "CTR",
        "definition":  "Click-Through Rate. Percentage of impressions that resulted in a click. Higher = stronger ad relevance.",
        "formula":     "SUM(clicks) / SUM(impressions)",
        "owner":       "Marketing Ops",
        "source_table":"fact_campaign_performance",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance → clicks / impressions",
    },
    {
        "kpi":         "CPC",
        "definition":  "Cost Per Click. Average cost paid per user click. Lower CPC = more efficient spend.",
        "formula":     "SUM(spend) / SUM(clicks)",
        "owner":       "Media Operations",
        "source_table":"fact_campaign_performance",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance → spend / clicks",
    },
    {
        "kpi":         "CPM",
        "definition":  "Cost Per Mille. Cost per 1,000 impressions. Standard media buying efficiency metric.",
        "formula":     "SUM(spend) / (SUM(impressions) / 1000)",
        "owner":       "Media Operations",
        "source_table":"fact_campaign_performance",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance → spend / (impressions / 1000)",
    },
    {
        "kpi":         "Conversion Rate",
        "definition":  "Percentage of clicks that resulted in a desired action (purchase, signup, etc.).",
        "formula":     "SUM(conversions) / SUM(clicks)",
        "owner":       "Growth Analytics",
        "source_table":"fact_campaign_performance",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance → conversions / clicks",
    },
    {
        "kpi":         "CPA",
        "definition":  "Cost Per Acquisition. Average spend required to generate one conversion.",
        "formula":     "SUM(spend) / SUM(conversions)",
        "owner":       "Growth Analytics",
        "source_table":"fact_campaign_performance",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance → spend / conversions",
    },
    {
        "kpi":         "Active Advertisers",
        "definition":  "Count of unique advertisers with at least one campaign record in the period.",
        "formula":     "COUNT(DISTINCT advertiser_id) WHERE spend > 0",
        "owner":       "Sales Strategy",
        "source_table":"fact_campaign_performance",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance → DISTINCT advertiser_id",
    },
    {
        "kpi":         "Pipeline Revenue",
        "definition":  "Total projected revenue across all open (non-closed) sales opportunities.",
        "formula":     "SUM(projected_revenue) WHERE stage NOT IN ('Closed Won','Closed Lost')",
        "owner":       "Sales Strategy",
        "source_table":"fact_sales_pipeline",
        "refresh":     "Weekly",
        "status":      "✓ Validated",
        "lineage":     "fact_sales_pipeline → projected_revenue",
    },
    {
        "kpi":         "Revenue vs Target",
        "definition":  "Actual revenue as a percentage of the monthly revenue target set in planning.",
        "formula":     "SUM(actual_revenue) / SUM(target_revenue) × 100",
        "owner":       "Ads Finance",
        "source_table":"fact_campaign_performance JOIN fact_budget_targets",
        "refresh":     "Daily",
        "status":      "✓ Validated",
        "lineage":     "fact_campaign_performance + fact_budget_targets → revenue / target_revenue",
    },
]
