"""Executive Brief — auto-generated findings and recommendations.

Rule-based decision engine: computes plan attainment, channel efficiency gaps,
CPC trends, and forecast trajectory from the warehouse, then renders them as an
executive-readable brief with a quantified budget reallocation recommendation.
"""
import streamlit as st
import numpy as np
import pandas as pd


def build_brief(query):
    """Returns (findings: list[str], recommendation: dict, risk: str)."""
    findings = []

    # Plan attainment
    attain = query("""
        SELECT SUM(c.revenue) AS actual, SUM(t.target) AS target FROM
        (SELECT month, SUM(revenue) AS revenue FROM fact_campaign_performance GROUP BY month) c
        JOIN (SELECT month, SUM(target_revenue) AS target FROM fact_budget_targets GROUP BY month) t
        USING (month)
    """).iloc[0]
    attain_pct = attain["actual"] / attain["target"] * 100
    findings.append(
        f"Revenue is at **{attain_pct:.0f}% of plan** YTD "
        f"(${attain['actual']/1e6:.1f}M actual vs ${attain['target']/1e6:.1f}M target)."
    )

    # Channel efficiency
    ch = query("""
        SELECT channel, SUM(revenue) AS revenue, SUM(spend) AS spend,
               SUM(revenue)/NULLIF(SUM(spend),0) AS roas
        FROM fact_campaign_performance GROUP BY channel ORDER BY roas DESC
    """)
    best, worst = ch.iloc[0], ch.iloc[-1]
    roas_gap = (best["roas"] / worst["roas"] - 1) * 100
    findings.append(
        f"**{best['channel']}** is the most efficient channel ({best['roas']:.2f}x ROAS), "
        f"outperforming **{worst['channel']}** ({worst['roas']:.2f}x) by {roas_gap:.0f}%."
    )

    # CPC trend on worst channel (H2 vs H1)
    cpc = query(f"""
        SELECT CASE WHEN month <= 6 THEN 'H1' ELSE 'H2' END AS half,
               SUM(spend)/NULLIF(SUM(clicks),0) AS cpc
        FROM fact_campaign_performance WHERE channel = '{worst['channel']}'
        GROUP BY 1 ORDER BY 1
    """)
    risk = None
    if len(cpc) == 2:
        cpc_chg = (cpc.iloc[1]["cpc"] / cpc.iloc[0]["cpc"] - 1) * 100
        if cpc_chg > 3:
            risk = (f"{worst['channel']} CPC is up **{cpc_chg:.0f}%** in H2 vs H1 — "
                    f"cost inflation on an already low-ROAS channel.")
        else:
            risk = (f"{worst['channel']} carries the weakest ROAS ({worst['roas']:.2f}x); "
                    f"CPC trend is stable ({cpc_chg:+.0f}% H2 vs H1) but efficiency remains the gap.")

    # Forecast trajectory (linear trend, exclude partial signal months)
    monthly = query("SELECT month, SUM(revenue) AS revenue FROM fact_campaign_performance GROUP BY month ORDER BY month")
    coef = np.polyfit(monthly["month"], monthly["revenue"], 1)
    slope_pct = coef[0] / monthly["revenue"].mean() * 100
    findings.append(
        f"Monthly revenue trend is **{slope_pct:+.1f}%/month**; "
        f"trajectory {'supports' if slope_pct > 0 else 'threatens'} the full-year plan."
    )

    # Recommendation: shift 15% of worst channel's spend to best channel
    shift = worst["spend"] * 0.15
    expected_gain = shift * (best["roas"] - worst["roas"])
    recommendation = {
        "text": (f"Reallocate **15% of {worst['channel']} spend (${shift/1e6:.2f}M)** to "
                 f"**{best['channel']}**."),
        "rationale": (f"{best['channel']} returns ${best['roas']:.2f} per dollar vs "
                      f"${worst['roas']:.2f} on {worst['channel']}."),
        "expected_gain": expected_gain,
        "caveat": ("Estimate assumes constant marginal ROAS; validate with the geo-holdout framework "
                   "in the Incrementality tab before committing full reallocation."),
    }
    return findings, recommendation, risk


def render(query):
    st.markdown("### 📋 Executive Brief — Auto-Generated")
    st.caption("Generated by the AdsPulse decision engine on every data refresh. "
               "Findings are computed, not hand-written.")

    findings, rec, risk = build_brief(query)

    col1, col2 = st.columns([3, 2])
    with col1:
        st.markdown("**Key Findings**")
        for f in findings:
            st.markdown(f"- {f}")
        if risk:
            st.markdown(f"- ⚠️ **Biggest risk:** {risk}")

    with col2:
        st.markdown("**Recommendation**")
        st.markdown(rec["text"])
        st.markdown(f"*{rec['rationale']}*")
        st.metric("Expected incremental revenue", f"${rec['expected_gain']/1e6:.2f}M")
        st.caption(rec["caveat"])
